f1 = float(input("Enter the Feet for the first piece of fabric: "))
i1 = float(input("Enter the Inches for the first piece of fabric: "))
f2 = float(input("Enter the Feet for the second piece of fabric: "))
i2 = float(input("Enter the Inches for the second piece of fabric: "))
i3 = int(i1 + i2)
f3 = int(i3 / 12)
i = str(i3 % 12)
f = str(int(f1 + f2 +f3))
print("Feet: " + str(f) + " Inches: " + str(i))
#Feet: # Inches: #
