n1 = int(input("Enter a number: "))
print("Largest: " + str(n1))
n2 = int(input("Enter a number: "))
print("Largest: " + str(max(n1,n2)))
n3 = int(input("Enter a number: "))
print("Largest: " + str(max(n1,n2,n3)))
n4 = int(input("Enter a number: "))
print("Largest: " + str(max(n1,n2,n3,n4)))
n5 = int(input("Enter a number: "))
print("Largest: " + str(max(n1,n2,n3,n4,n5)))
n6 = int(input("Enter a number: "))
print("Largest: " + str(max(n1,n2,n3,n4,n5,n6)))
